apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: example-secret-store
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      # azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: "64dc69e4-d083-49fc-9569-ebece1dd1408"
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "https://secret-store-nrf8uetnyi.vault.azure.net/"
      authSecretRef:
        # points to the secret that contains
        # the azure service principal credentials
        clientId:
          name: azure-secret-specho
          namespace: external-secrets
          key: ClientID
        clientSecret:
          name: azure-secret-specho 
          namespace: external-secrets
          key: ClientSecret