apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-machinesets
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: ''
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/configs/machinesets
    repoURL: 'https://github.com/cnuland/aro-hello-chris-tekton-chains.git'
    targetRevision: HEAD
    directory:
      recurse: false
  ignoreDifferences:
  - group: machine.openshift.io
    kind: MachineSet
    jsonPointers:
    - /spec/template/spec/providerSpec/value/image
    - /spec/template/spec/providerSpec/value/publicIP
    - /spec/template/spec/providerSpec/value/networkResourceGroup
    - /spec/template/spec/providerSpec/value/vnet
    - /spec/template/spec/providerSpec/value/publicLoadBalancer
    - /spec/template/spec/providerSpec/value/resourceGroup
    - /spec/template/metadata/labels
    - /spec/selector/matchLabels
    - /metadata/labels
  project: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    automated:
      prune: false
      selfHeal: false