apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: openshift-gitops-argocd-extended-clusterrole
rules:
  - apiGroups:
    - ""
    resources:
      - resourcequotas
      - limitranges
      - namespaces
    verbs:
      - '*'
  - apiGroups:
    - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs:
      - '*'
  - apiGroups:
    - machine.openshift.io
    resources:
      - MachineSet
    verbs:
      - '*'
  - apiGroups:
    - operator.tekton.dev
    resources:
      - tektonchains
    verbs:
      - '*'
  
  - apiGroups:
    - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'