kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: kyverno-allow-priviledged-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allow-priviledged-scc
  # name: openshift-gitops-argocd-extended-clusterrole
subjects:
  - kind: ServiceAccount
    name: kyverno
    namespace: kyverno
  - kind: ServiceAccount
    name: kyverno-cleanup-controller
    namespace: kyverno
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno