apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: ''
    namespace: 'external-secrets'
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/operators/external-secrets/overlays/default
    repoURL: 'https://github.com/cnuland/aro-hello-chris-tekton-chains.git'
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
