apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-chris
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    name: ''
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/hello-chris
    repoURL: 'https://github.com/cnuland/aro-hello-chris-tekton-chains.git'
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true